### PR TITLE
Upgrading go version from 1.17 to 1.18.3

### PR DESCRIPTION
**Pull request by mikolajprzybysz**
This PR bumps following images:
`go/Dockerfile`, `go/Dockerfile.ubi` and `pulumi/Dockerfile` which build successfully,
along go version upgrade in .github workflow

https://tip.golang.org/doc/go1.18#:~:text=Go%201.18%20includes%20an%20implementation,compatible%20%2D%20changes%20to%20the%20language.
> Go 1.18 includes an implementation of generic features as described by the [Type Parameters Proposal](https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md). This includes major - but fully backward-compatible - changes to the language.

### CODE REVIEW

**Review by RobbieMcKinstry — APPROVED** [review]
Awesome! Looks good to me!

**Comment by mikolajprzybysz** [comment]
> Awesome! Looks good to me! Looks like tests are failing, however. Not sure what's going on there.

@RobbieMcKinstry tests are failing as they are missing PULUMI_ACCESS_TOKEN
```
containers_test.go:36: PULUMI_ACCESS_TOKEN not found, aborting tests.
```

this is not related to the change I made

**Comment by mikolajprzybysz** [comment]
> @mikolajprzybysz would it be okay with you if I closed this PR in lieu of #97 ? My understanding is that Secrets are not accessible to PRs from forked repositories. If that's truly the case, I'm not sure how we haven't encountered this sooner. I'm going to open an issue to inspect and address.
> 
> In the meantime, we can get your changes in by using a branch PR instead of a fork PR, if that's okay with you! :)

@RobbieMcKinstry fine by me! I am for anything that helps merge this change in :)

**Comment by RobbieMcKinstry** [comment]
Thanks very much for understanding! I opened https://github.com/pulumi/pulumi-docker-containers/issues/98 to track the cause of the failed CI checks. :)

**Comment by mikolajprzybysz** [comment]
@RobbieMcKinstry  could you release it as new version as well, I would like to use it to update [pulumi-kubernetes-operator](https://github.com/pulumi/pulumi-kubernetes-operator) as well

**Comment by RobbieMcKinstry** [comment]
Hey there @mikolajprzybysz ! Today I learned that this repository is released in lock-step with the `pulumi` CLI.
During the [release process for the CLI](https://github.com/pulumi/pulumi/blob/master/.github/workflows/release.yml#L432), we build these Docker images and release them to the image repositories with tags that mirror the CLI release.

That is to say, you can expect this PR to make its way into `v3.36.0` which is expected to release later this week. I will update the README with this information.

**Pull request merged**
